HenrikJoreteg/hjs-webpack

README.md, index.js, lib/base-config.js, package.json
This uses `autoprefixer-core` and `postcss-loader` to add autoprefixing to stylus, less and plain css. This also removed autoprefixer-stylus since that is no longer necessary.
closes #12
=> Autoprefix all configured style loaders

lib/base-config.js
I don't having this extension here is necessary since we set up `.styl` as a loader elsewhere. http://webpack.github.io/docs/configuration.html#resolve-extensions
=> dont need .styl extension in resolve

README.md, package.json
We reference the `json-loader` in the [base config](https://github.com/HenrikJoreteg/hjs-webpack/blob/c8d40cbdada54bc243ef382871a970f0a997d50a/lib/base-config.js#L34), so I think it should be installed to peer deps.
The other option is to add something to the "Other loaders" section, but requiring `.json` files seems common enough that we should support it as easily as possible.
=> add json-loader to peer deps

lib/get-package.js
I think this is the problem with #20, where the `PWD` env var doesn't exist so it find the `package.json` for `hjs-webpack` instead. This switches to the node builtin method of getting the current working directory.
Fixes #20
=> use process.cwd() over env var for root

examples/assets-and-index-html/package.json, examples/just-assets-no-html/package.json, examples/prerendered-html-files/package.json, package.json
**What this does:**
- separate example package.json files in to devDeps and deps
- use full list of deps generated from `npm install hjs-webpack` for devDeps
**Why:**
So while digging into #22 I found this strange behavior. If I took the code for the `prerendered-html-files/src` example and separated it into its own folder and used the `package.json` from this PR, then the example worked. But running `npm install` in the directory if it has just `"dependencies": {"hjs-weback": "latest"}` did not work. From what I could tell, all the same modules were being installed.
The description in #22 is correct, turning off the `DedupePlugin` makes the build work. I also found the commenting out `require('ampersand-router')` also made the build work. I'm not exactly sure but it seems like some …
=> Fix for example deps

lib/base-config.js
This is the only change I've needed so far. Is there a reason (use case) for having `.jsx` registered with the babel loader but not as a resolvable extension?
=> Resolve .jsx files

README.md, index.js
Maybe you don't like Sass but it is widely used.
It was simpler to add it than add a generic loader mechanism in user config, but if you want that capability, I can maybe do it
=> add .scss loader, don't install by default.

README.md
The module `react-hot-loader` depends on `react-hot-api` that has `react` on peerDependencies.
=> Add react to peer modules command

index.js, lib/is-installed.js, lib/optional-loaders.js
Loaders and `react-hot`(#50) are only added to the webpack config if they are installed.
To do this I extracted all "optional" loaders into `lib/optional-loaders.js` and load these conditionally using the `isInstalled` function from `lib/is-installed.js`.
=> Conditional load optional loaders

index.js
Very simple fix, maybe too simple ;)
Background: This enables usage like this
```
node -p 'require("./webpack.config.js")'
node -p 'JSON.stringify(require("./webpack.config.js"), 0, 2)' > webpack-config-gen.json
```
to inspect the actual configuration generated by `hjs-webpack`. 
Very handy for people like me using this to get started with `webpack` in general (btw :heart: thanks for this very nice headstart), but then want to learn what actually goes on.
=> fix when no process.argv[1] is present

index.js, package.json
Closes #62, #63 
Using `^1.3.0` as the version for `react-hot-loader` in peer deps since the change to remove `NoErrorsPlugin` only landed in that version.
=> Hot loader and source map

README.md, index.js
I'm in a situation where I'm integrating with Amazon's cloud drive api, and the api requires all hosts calling it to be https.  webpack-dev-server supports https, so I've added a configuration flag (defaulted to false to preserve http mode), documentation, and the code necessary to support either mode.
=> Adding optional support for webpack-dev-server's https mode

README.md, lib/base-config.js
Resolves #67, including my personal favorite LiveScript, @jest's preferred setup with CJSX, then also CoffeeScript and TypeScript. I also DRYed up the extensions regex a little and made it more consistent.
=> add optional support for more compile-to-JS languages

README.md
Adds a documentation section for how to extend the hjs-webpack config, with an example covering all the issues that have been brought up so far. Although this may change in the future I think it's a good idea to document the best way to do it currently. Also removes the other loaders section since that is now addressed by #80.
Closes #57, closes #61
=> add doc section with example for extending webpack config

CHANGELOG.md, README.md, lib/html-plugin.js
I ran into an issue when trying to build this as part of a project where my target build directory was as a "child" of another static site. This lets me run options like this:
```js
module.exports = getConfig({
in: 'presentation/root.js',
out: '../../public/evolution-of-the-web-app',
clearBeforeBuild: '!(images|static)',
hostname: hostname || 'odin.local',
port: port || 3000,
html: function (context) {
return context.defaultTemplate({
html: '<div>' + React.renderToString(React.createElement(Presentatation)) + '</div>',
head: '<link href="https://fonts.googleapis.com/css?family=Oswald:700" rel="stylesheet" type="text/css">',
publicPath: context.isDev ? '/' : '/evolution-of-the-web-app/'
})
}
})
```
Note that the `out` is outside of this directory, it lets me run the slides for one of my …
=> removed default option from template function, and added publicPath option to replace it

examples/assets-and-index-html/src/styles.styl, examples/prerendered-html-files/webpack.config.js
- Fixing bad route for background-image on `assets-and-index-html` examples
- Fixing issue with babel core on `prerendered-html-files` example
@lukekarrys : I couldn't figure out what was going on on example number 2. I'm getting a 404 error when I hit `http://localhost:3000`
=> Fixing assets-and-index-html and prerendered-html-files examples

CHANGELOG.md, README.md, lib/base-config.js
this is pretty neat, IMO. But... i'm not quite 100% on the particulars of how I added it. 
But, adding it first is what enables you to write code inside the worker as ES6, which is pretty sweet.
Feedback on code and docs appreciated.
When built, it comes out as separate chunk, just like fonts, etc.
=> add worker loader

lib/base-config.js
I've been using react-bootstrap which requires bootstrap which tries to load a ``woff2`` file, ``glyphicons-halflings-regular.woff2``. This seems to fix the problem.
=> Load .woff2 files with url-loader

lib/base-config.js
- Separate them into individual loaders. This will make it easier for users to make changes to ones if they need to.
- Add mimetypes for extensions that I saw in documentation for other projects. I noticed `url-loader` sometimes infers different ones.
- Allow query strings for font loaders since many projects use those.
I looked at [`bootstrap-webpack`](https://github.com/bline/bootstrap-webpack) and [`font-awesome-webpack`](https://github.com/gowravshekar/font-awesome-webpack) to get examples of how other projects suggest to setup loaders and I was able to match both of those with the new loaders.
I created an [example gist](https://gist.github.com/lukekarrys/5bbeafcc4d23ed87ea76#file-readme-md) where I was able to get `hjs-webpack` working with both bootstrap and font-awesome.
Closes …
=> make some changes to font loaders

index.js
This addresses https://github.com/HenrikJoreteg/hjs-webpack/issues/123, I believe.
I say I believe because I'm having trouble testing my module via `npm link`.  I tested it by editing the `npm install`ed index.js in my node_modules directory.
=> Conditionally adding hot-loader to coffee in addition to jsx

README.md, bin/hjs-dev-server.js, examples/assets-and-index-html/.babelrc, examples/assets-and-index-html/package.json, examples/just-assets-no-html/package.json, examples/just-assets-no-html/webpack.config.js, examples/prerendered-html-files/package.json, index.js, lib/base-config.js, lib/installed-hot-loaders.js, package.json
This is the PR for resolving #65. I tried to do the following things
* Provide own binary `hjs-dev-server` which replaces `webpack-dev-server`
* Make upgrading as simple as possible
* Upgrade two examples to use the new hot reloading (`assets-and-index-html`, `prerendered-html-files) and upgrade one to not use hot reloading (`just-assets-no-html`)
* Add upgrade guide in the readme
Things are working well for me locally, but now I need some more eyes on this, especially to check if this is all in line with the project. 
**Update:** Still missing `https` support at the moment.
=> Move from react-hot-loader to react-transform

README.md, lib/html-plugin.js
If the lang option is set, the document will be generated with
a <html lang=""> tag and a closing </html> tag. If the option
is not set the <html> tag will be omitted as before.
closes #146
=> Add lang as an option to defaultHtml

lib/installed-hot-loaders.js
There were two issues with using hmr this on npm2:
1. We were resetting the hot flag on the config if all the base loaders were not resolvable. npm3 moves all the base loaders to the top level so no problem there, but npm2 leaves them nested. The fix was to check if the preset was resolvable like we do before throwing the warning error.
2. We list `webpack-hot-middleware` as a dep so we can avoid having the user need to install one more thing. But again on npm2 the middleware couldn't be found since it was nested. The fix was to resolve this as well with `require.resolve`.
fixes #161
=> check for preset and use full hot middleware entry path

README.md
While it's possible to assign arbitrary names to import'ed/require'd functions,
using the same name (``getConfig``) everywhere avoids confusion.
=> Use getConfig consistently

lib/html-plugin.js
As `document.body` is no longer used as a default mount point,
move `<script>` inside the `<body>` so the DOM validates
Closes #177
=> Move <script> tag inside <body>

README.md, lib/html-plugin.js
If you want to enable zoom on mobile for UA reasons provide
```
metaViewport: {
userScalable: true
}
```
as an option to the `defaultHtml` function
Closes #176
=> Add option for setting user-scalable to "yes"

README.md, bin/hjs-dev-server.js, package.json
The webpack-dev-server has support for proxies, but this feature seems to be missing from hjs-webpack so I figured it'd be nice to add that too :)
=> Add support for http-proxy-middleware

README.md
This just updates the documentation for #177, inlining the script into the body tag and clarifying the default naming of the css and js bundles.
=> Correct the default HTML output

README.md, lib/base-config.js
jade had to be renamed to pug, see https://github.com/pugjs/pug/issues/2184 for more details.
This commit will replace `jade-loader` with `pug-loader`, which supports the
extensions `.pug` and `.jade` for backwards compatibility.
=> use pug-loader instead of jade-loader

index.js
Is there a good reason why we replace all environment variables in production with `NODE_ENV: "production"`? I use hjs-webpack to build server-side code and need to be able to read environment variables. I suggest that we only replace `process.env.NODE_ENV` with `"production"`  instead.
=> Retain environment variables in production

index.js
This commit adds support for using different NODE_ENV values than
"production" when running the `DefinePlugin`. It now sets `NODE_ENV`
to whatever the environment variable `NODE_ENV` is, and defaults to
"production" if `NODE_ENV` is not set.
Fixes #328.
=> Add support for several different NODE_ENV values

bin/hjs-dev-server.js
This is maybe an edge case, but I have several times run into CORS trouble when requesting static files from the dev server from the main js script when the main js script is run on a page on a different domain. This pull request should solve that.
=> Add CORS headers to response on static files served by dev server

CHANGELOG.md, lib/installed-style-loaders.js, package.json
This is a proposed solution for issue #326 
Look for a `postcss.config.js` file in the cwd of the process running hjs-webpack (typically the same as `package.json` where PostCSS expects the file to be) and use it to build the options given to the loader. 
This change lets users define custom PostCSS-plugins via `postcss.config.js` instead of modifying the config generated by `hjs-webpack`.
=> Honor the plugins option in postcss.config.js

.gitignore, index.js, package.json
Hey!
This is a very simple PR 😄 I'm just updating the dependencies and using UglifyJS from its own package and not the version from `webpack.optimize` since it doesn't support ES6 yet. 
Thanks!
=> Update dependencies and support ES6
